[tools]
go = "1.23"

[tasks.build]
sources = ["./*.go"]
outputs = { auto = true }
env.CGO_ENABLED = 0
env.GOOS = "linux"
env.GOARCH = "amd64"
run = "go build -a -tags netgo -ldflags '-w' ."

[tasks."test"]
run = "echo $(whoami)"

[tasks."docker:remove-env"]
run = "rm docker.env"

[tasks."docker:build"]
sources = ["drone-slack", "Dockerfile"]
outputs = { auto = true }
depends = ["build"]
run = "docker build --rm -t gowerstreet/slack:local ."

[tasks."docker:run"]
env.PLUGIN_CHANNEL = "foo"
env.PLUGIN_USERNAME = "drone"
env.PLUGIN_STATUS = "success"
env.PLUGIN_DESCRIPTION = "test description"
env.PLUGIN_WEBHOOK = "{{env._SLACK_ALERTS_WEBHOOK}}"
env.CI_REPO_OWNER = "octocat"
env.CI_REPO_NAME = "hello-world"
env.CI_COMMIT_SHA = "7fd1a60b01f91b314f59955a4e4d4e80d8edf11d"
env.CI_COMMIT_BRANCH = "master"
env.CI_COMMIT_AUTHOR = "octocat"
env.CI_COMMIT_AUTHOR_EMAIL = "$(whoami)@gower.st"
env.CI_COMMIT_AUTHOR_AVATAR = "https://avatars0.githubusercontent.com/u/583231?s=460&v=4"
env.CI_COMMIT_AUTHOR_NAME = "The Octocat"
env.CI_COMMIT_MESSAGE = "A test commit\n\nWith a line break\nAnd another line break"
env.CI_COMMIT_TAG = "1.0.0"
env.CI_PIPELINE_NUMBER = 1
env.CI_PIPELINE_URL = "http://ci.gower.st/repos/120935/pipeline/18"
#env.CI_COMMIT_PULL_REQUEST = 1
#env.CI_COMMIT_SOURCE_BRANCH = "pull_request_branch"
depends = ["docker:build"]
depends_post = ["docker:remove-env"]
run = ["env | grep -E '^(CI_|PLUGIN_)' > docker.env",
       "docker run --env-file docker.env gowerstreet/slack:local"]


[env]
SLACK_WEBHOOK = { value = "{{env._SLACK_ALERTS_WEBHOOK}}", redact = true }
