# escape=`
FROM plugins/base:windows-1909-amd64@sha256:d8421c306bb34bbc95dd8587617cc0dfdaa09059b6d96ee00ff5966a4a4e54f4

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Slack" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-slack.exe C:/bin/drone-slack.exe
ENTRYPOINT [ "C:\\bin\\drone-slack.exe" ]
