# escape=`
FROM plugins/base:windows-ltsc2022-amd64@sha256:b0e662a71fbe8a28147fae27a68aa4bc5236c02bbe3400513bbefdb0469a50ce
USER ContainerAdministrator

ENV GODEBUG=netdns=go

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Slack" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-slack.exe C:/drone-slack.exe
ENTRYPOINT [ "C:\\drone-slack.exe" ]