# escape=`
FROM plugins/base:windows-1909-amd64@sha256:cc9c5d1cd7e17e16920c413888bbb1251e1ed38e91be8d1a1cf8dbc35865130b

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Slack" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-slack.exe C:/bin/drone-slack.exe
ENTRYPOINT [ "C:\\bin\\drone-slack.exe" ]
