FROM alpine:3.20

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Slack" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

# Update apk repositories and install git
RUN apk add --no-cache git bash

# Add the Drone Slack binary
ADD release/linux/amd64/drone-slack /bin/

# Set the entrypoint for the Drone Slack binary
ENTRYPOINT ["/bin/drone-slack"]
