FROM plugins/base:multiarch@sha256:f3e7254fed81b6138b845508e527189ab8005314e17b4aa78bea03fa1cc227ac

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Slack" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-slack /bin/
ENTRYPOINT [ "/bin/drone-slack" ]
