# escape=`
FROM plugins/base:windows-1903-amd64@sha256:338cdba56a7f30d721b6567d382b95465642993f85564cb385e65b2f3f84352c

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Slack" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-slack.exe C:/bin/drone-slack.exe
ENTRYPOINT [ "C:\\bin\\drone-slack.exe" ]
