# escape=`
FROM plugins/base:windows-1809-amd64@sha256:61095306fa56d51adc841f2b0f93f511efb5792d12f2549bb2eb1cbce02c1f05
USER ContainerAdministrator

ENV GODEBUG=netdns=go

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Slack" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-slack.exe C:/drone-slack.exe
ENTRYPOINT [ "C:\\drone-slack.exe" ]