FROM plugins/base:multiarch@sha256:bc400790f20bb35b340a3b4102dfac34b523795389c7c35d99f862acde5cf4ee

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Slack" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm/drone-slack /bin/
ENTRYPOINT [ "/bin/drone-slack" ]
